### ISSUE TITLE
After creating a dataset, the screen remains dark/disabled

### ISSUE THREAD

**Issue by lizlooney** [FIRST-Tech-Challenge/fmltc#101]
![Screen Shot 2021-09-08 at 1 29 08 PM](https://user-images.githubusercontent.com/397725/132580832-070faa10-1749-4afa-b07b-512463602e6e.png)

**Comment by cmacfarl** [comment]
Guessing that tab needs a fix similar to https://github.com/FIRST-Tech-Challenge/fmltc/pull/90.  @hardcopi?

**Comment by hardcopi** [comment]
Yes... I have a fix, just need to finish up another part. I'll have it up tomorrow.

**Comment by lizlooney** [comment]
I figured it out! Yep it was just like #90.

**Comment by lizlooney** [comment]
Fixed by PR #104
