### ISSUE TITLE
Labeling Problems and Suggestions

### ISSUE THREAD

**Issue by uvidyadharan** [FIRST-Tech-Challenge/fmltc#159]
# Ghosting with bounding boxes

There is a "ghosting" effect when adjusting the bounding box when labeling a video. This all goes away when the left click is released but is an issue nonetheless. This is more prevalent in lower resolution videos.  

## Original Image

![image](https://user-images.githubusercontent.com/55924756/138334876-03a9f13d-958e-4fc5-89ad-d96998f88c55.png)

## Typical Ghosting

![image](https://user-images.githubusercontent.com/55924756/138335066-190218fc-43c2-4936-842e-85746665c3e6.png)

## Overwriting Other Bounding Boxes

![image](https://user-images.githubusercontent.com/55924756/138335320-8d722c0a-92ac-4cc4-b060-06871873f60f.png)

## Low Resolution Frames

![image](https://user-images.githubusercontent.com/55924756/138336109-4108f65b-b2fb-4c5f-8ccb-23a10a7d0107.png)

This is at 320 x 240. It is important to see how the static width of the bounding box makes the smearing worse. Perhaps the width of the bounding box should change dynamically with resolution. 

# Bounding Box Deselects When Cursor Goes Off Screen

When dragging one of the corners of a given bounding box the entire box will be deselected if the cursor moves off screen. When drawing a bounding box around an image that is near the edge of the frame this can be frustrating. 

https://user-images.githubusercontent.com/55924756/138337355-88a2a68d-a16e-4d6f-b8db-35a2d2933328.mp4

# Differentiating Bounding Boxes

As of now there is no way to tell which bounding box has which label and which entry it is on the table. The only way to do this right now is to move a corner of a bounding box and see which entry on the table changes. I would recommend employing some sort of color coding system in which each object is assigned a color and when hovering over a label corner a popup will show up showing its Label and which entry it is on the table. 

# Batch Editing Tools 

## Clear All Labels on Video

As of now the only way to do this is to delete the video and reupload it. Suffice to say this is not the most ideal way to clear the labels on a video. This is especially useful in a case where one forgets to turn off the Auto Tracking and the entire video gets labeled unproperly. 

## Clear All Instances of a Specific Label on Video

A user can easily accidentally enter a label they did not intend to and just want to remove all instances of that one label but keep the rest. As of now there is no easy way to do that without going frame by frame

## Modify All Instances of a Specific Label on a Video

When labeling multiple videos all going to the same dataset it is important that the labels match up for the same object. However a small typo can easily be made. As of now there is no way to change all instances of one label to another so the user would be forced to go frame by frame renaming each instance of that label.

**Comment by texasdiaz** [comment]
These are great suggestions. One other suggestion brought up informally is to show "crosshairs" on the mouse pointer that run vertical and horizontal when the mouse is over the image frame area. That would help align the bounding boxes to irregular-shaped objects so you could get the bounding boxes as tight as possible.
