### ISSUE TITLE
Job State does not automatically refresh on the status page any more

### ISSUE THREAD

**Issue by texasdiaz** [FIRST-Tech-Challenge/fmltc#190]
The last time I ran a job, I noticed that the job was in the QUEUED state for a LONG period of time. When I refreshed the page, I realized the job had completed with a SUCCESS already. The next time I ran a job, I pressed "refresh" on the browser every 2-3 minutes, and I saw the Job State change with each refresh. Once training started (the RUNNING state) the model looked like it was running for 48 minutes and still going (the timer was 48 minutes), but when I refreshed the screen it said it succeeded at 14:33 minutes.

**Comment by lizlooney** [comment]
@texasdiaz Were you looking at the Models tab of the main page that shows the list of all models? Or, were you looking at the page that has Details, Graphs, and Images tabs?

**Comment by texasdiaz** [comment]
@lizlooney I was looking at the models tab of the main page that shows the list of all models. I had multiple models in progress most of the time, but my last run I had only a single model in progress.
