### ISSUE TITLE
Steps must be multiple of 100

### ISSUE THREAD

**Issue by AlexKaiser26** [FIRST-Tech-Challenge/fmltc#291]
If you try to put in 1413 or any number that is not a multiple of 100 it will continue to train the model until 1413, then on the dashboard it will say 1500 steps and will result in 0 learning with 0 confidence on any image.

**Comment by texasdiaz** [comment]
That is partially correct. Steps must be in a multiple of 100. However, "0 learning with 0 confidence on any image" has nothing to do with the Steps used for training and everything to do with the content used to train the model. Please start an [FTC Community Forum](https://ftc-community.firstinspires.org/) thread if you want me to help you with training your model.

**Comment by AlexKaiser26** [comment]
Whenever I try to view images or graphs it is all at 1500 steps which shows 0 learning on the graphs and 0 confidence on the images.
If it was made to force it to be a multiple of 100 then this wouldn’t be a issue

**Comment by AlexKaiser26** [comment]
My model was training fine until it finished and was at 1500 steps.

**Comment by texasdiaz** [comment]
What's your team number?

**Comment by AlexKaiser26** [comment]
10464

**Comment by texasdiaz** [comment]
Wow, you're right, there's something very weird going on there. It's as if your last save point in that model just got utterly trashed. It looks like you've got a pretty decent model with your 1500 step model, so I'm glad to see it didn't stop you from proceeding. We'll look into it, and if you find yourself needing the 24 minutes back let me know.

Though, I must admit, your Teddy Bear / Zebra / Chair models are all standard categories recognized by the stock Model Zoo already. Have you tried using the stock pre-trained Model Zoo model to detect those objects? More on where to find the TensorFlow 2.x stock Model Zoo models here:
https://ftc-community.firstinspires.org/t/tensorflow-model-zoo-models/159/2

-Danny

**Comment by AlexKaiser26** [comment]
I tried the stock zoo model before I trained it which is why I used those images, it wasn't working and started detecting the poles and actual people as zebra's so I'm not sure what the issue was there. Thanks for your help though.
