### ISSUE TITLE
JS Deploy Creates invalid Date

### ISSUE THREAD

**Issue by AustinShalit** [FIRST-Tech-Challenge/fmltc#39]
https://github.com/FIRST-Tech-Challenge/fmltc/blob/0e55cc8acce2845e27066ce85a87527515bdc038/scripts/deploy_js.sh#L34

`date +%s%3N` is invalid on macOS. I think what the date should be is something more like `date +%s`.

**Comment by lizlooney** [comment]
Fixed with PR #72
